name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod download
      - name: Build Windows Binary
        run: GOOS=windows GOARCH=amd64 go build -o notes.exe .
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: notes-windows
          path: ./notes.exe
