name: Build Notes CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        include:
          - os: windows
            ext: .exe
          - os: linux
            ext: ""
          - os: darwin
            ext: ""

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod download
      - name: Build ${{ matrix.os }}
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=amd64 go build -o dist/notes${{ matrix.ext }} .
      - name: Upload ${{ matrix.os }} binary
        uses: actions/upload-artifact@v4
        with:
          name: notes-${{ matrix.os }}-amd64
          path: dist/notes${{ matrix.ext }}
